# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urls',
            name='httpurl',
            field=models.URLField(null=True),
        ),
    ]
